spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-201904c
    username: postgres
    password: postgres

server:
  servlet:
    context-path: /ec-201904c