spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-201904c
    username: postgres
    password: postgres
  mail:
    host: localhost
    port: 25
    properties:
      mail:
        from: noreply@example.com
  jmx:
      default-domain: ec-emp-management

server:
  servlet:
    context-path: /ec-201904c
  